# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: 编译Mycat镜像
        run: |
          wget https://raw.githubusercontent.com/AlphaYu/Adnc/master/doc/mycat/Dockerfile
          docker build -t 1635537446/mycat:1.6.7.6 .

      - name: 登录dockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: 推送
        run: |
          docker push 1635537446/mycat:1.6.7.6  
